apiVersion: v1
kind: Secret
metadata:
  name: reloop-secret
  labels:
    app.kubernetes.io/name: reloop
    app.kubernetes.io/part-of: reloop-app
type: Opaque
stringData:
  JWT_SECRET: "supersecretkey"
